### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by salihyanikgonul** [honlin96/Qubit-Tic-Tac-Toe#1]
Develop a user interface for the game, possibly on **pygame** backend

**Comment by salihyanikgonul** [comment]
We need some sort of GUI.

**Comment by honlin96** [comment]
The first GUI. 
![GUI](https://user-images.githubusercontent.com/37786219/66732018-ca659d80-ee8c-11e9-96c2-42d7c5c7f2f1.png)
